"""fix_repository_columns

Revision ID: f647086c8e6a
Revises: a6a3fb9efaae
Create Date: 2026-02-27 19:55:22.572904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f647086c8e6a'
down_revision: Union[str, Sequence[str], None] = 'a6a3fb9efaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_conversations', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('code_entities', 'interestingness_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('modules', 'detection_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('modules', 'file_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('modules', 'line_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('repositories', sa.Column('owner', sa.String(length=255), nullable=True))
    op.add_column('repositories', sa.Column('primary_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('repositories', sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repositories', sa.Column('size_files', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('size_lines', sa.Integer(), nullable=True))
    op.drop_column('repositories', 'file_count')
    op.drop_column('repositories', 'line_count')
    op.drop_column('repositories', 'primary_language')
    op.add_column('wiki_pages', sa.Column('source_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('wikis', 'module_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('wikis', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('wikis', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wikis', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('wikis', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('wikis', 'module_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('wiki_pages', 'source_files')
    op.add_column('repositories', sa.Column('primary_language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('line_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('file_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('repositories', 'size_lines')
    op.drop_column('repositories', 'size_files')
    op.drop_column('repositories', 'last_analyzed_at')
    op.drop_column('repositories', 'primary_languages')
    op.drop_column('repositories', 'owner')
    op.alter_column('modules', 'line_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('modules', 'file_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('modules', 'detection_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('code_entities', 'interestingness_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('chat_conversations', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###
